import Link from 'next/link';
import { ArrowDown, ArrowRight, BookOpen, Eye, Feather } from 'lucide-react';
import { SiteFooter } from '@/components/site/site-footer';
import { SiteHeader } from '@/components/site/site-header';

const dispatches = [
  { date: '18 August 2026', title: 'Regarding the disturbances beneath Highgate', summary: 'The official account mentions subsidence. The archive is less certain.' },
  { date: '02 July 2026', title: 'A field note from Prague', summary: 'Three vanished ledgers, a locked reading room, and one entirely innocent raven.' },
  { date: '21 May 2026', title: 'The Lazarus papers: first fragments', summary: 'Newly recovered pages complicate an already inconvenient version of history.' },
];

export default function Home() {
  return <main><SiteHeader transparent />
    <section className="hero" aria-labelledby="hero-title"><div className="hero-image" aria-hidden="true" /><div className="hero-shade" aria-hidden="true" /><div className="hero-grid" aria-hidden="true" />
      <div className="hero-content shell"><p className="eyebrow reveal">The concealed histories · Archive I</p><h1 id="hero-title" className="reveal reveal-delay-1">History is only what <em>survived</em> being hidden.</h1><p className="hero-deck reveal reveal-delay-2">The Shadowverse documents the supernatural conflicts that shaped our world—and the ancient institution devoted to ensuring you never hear of them.</p><div className="hero-actions reveal reveal-delay-3"><Link className="button button-gold" href="/books">Enter the archive <ArrowRight size={16} /></Link><Link className="text-link light" href="/about-toby#the-shadowverse">What is The Shadowverse?</Link></div></div>
      <a className="scroll-cue" href="#featured" aria-label="Continue to featured book"><span>Continue</span><ArrowDown size={15} /></a><p className="hero-folio">SV / 001</p>
    </section>
    <section className="premise-section"><div className="shell premise-grid"><p className="section-index">01 / The premise</p><div><p className="display-quote">There is another world beneath ours. It has its own wars, its own monsters, and its own version of the truth.</p><p className="muted-copy">Naturally, there is no reliable evidence to support any of this. An organisation dedicated to erasing such evidence would presumably consider that a success.</p></div></div></section>
    <section className="featured-book section-pad" id="featured"><div className="shell book-feature-grid"><div className="book-stage"><div className="sigil" aria-hidden="true">✦</div><div className="book-cover" role="img" aria-label="The Lazarus Covenant book cover"><span className="book-kicker">The Shadowverse · Book One</span><strong>The Lazarus<br />Covenant</strong><span className="book-mark" aria-hidden="true">V</span><span className="book-author">Toby Crome</span></div><span className="book-shadow" aria-hidden="true" /></div><div className="book-copy"><p className="eyebrow brass">Featured record · File 001</p><h2>The Lazarus Covenant</h2><p className="book-position">Book one of The Shadowverse</p><p>When seventeen-year-old Mara Vane discovers a name erased from every public record, she is drawn into the century-old war between the Conclave and the Paragons—and a secret her family has died to protect.</p><blockquote>“The dead keep better records than the living.”</blockquote><dl className="metadata-row"><div><dt>Status</dt><dd>Coming soon</dd></div><div><dt>Release</dt><dd>14 October 2027</dd></div></dl><Link className="button button-ink" href="/books/the-lazarus-covenant">Examine the record <ArrowRight size={16} /></Link></div></div></section>
    <section className="gateways section-pad"><div className="shell"><div className="section-heading"><div><p className="eyebrow brass">Beyond the known record</p><h2>Explore the Shadowverse</h2></div><p>Choose your point of entry. None are entirely safe.</p></div><div className="gateway-list"><Link href="/books" className="gateway"><span>01</span><BookOpen /><h3>The Books</h3><p>Read the stories they failed to suppress.</p><ArrowRight /></Link><Link href="/characters" className="gateway"><span>02</span><Eye /><h3>The Dossiers</h3><p>Meet allies, enemies, and uncertain cases.</p><ArrowRight /></Link><Link href="/about-toby#the-shadowverse" className="gateway"><span>03</span><Feather /><h3>The Lore</h3><p>Trace the war hidden inside our history.</p><ArrowRight /></Link></div></div></section>
    <section className="dispatches section-pad"><div className="shell"><div className="section-heading light-heading"><div><p className="eyebrow">Recently unsealed</p><h2>From the archive</h2></div><Link href="/news" className="text-link light">View all dispatches <ArrowRight size={15} /></Link></div><div className="dispatch-grid">{dispatches.map((item,index)=><article key={item.title} className="dispatch-card"><div className="dispatch-number">0{index+1}</div><time>{item.date}</time><h3>{item.title}</h3><p>{item.summary}</p><Link href="/news">Read report <ArrowRight size={14} /></Link></article>)}</div></div></section>
    <section className="myriad-strip"><div className="shell myriad-inner"><div><p className="eyebrow brass">A parallel investigation</p><h2>Prefer your conspiracies without the supernatural?</h2></div><a href="https://example.com" target="_blank" rel="noreferrer" className="button button-outline">Enter The Myriad <ArrowRight size={16} /></a></div></section><SiteFooter />
  </main>;
}
