export type Book={slug:string;title:string;series:string;position:number;description:string;extended:string;quote:string;release:string;status:string;isbn?:string;accent:string};
export const books:Book[]=[
 {slug:'the-lazarus-covenant',title:'The Lazarus Covenant',series:'The Concealed Histories',position:1,description:'A vanished name. A forbidden archive. A war that has never officially existed.',extended:'When Mara Vane finds her late father’s handwriting in a ledger sealed for a century, she follows it beneath London and into the custody of the Conclave. There she learns that history has been edited—and that the thing called Lazarus was never truly buried.',quote:'The dead keep better records than the living.',release:'14 October 2027',status:'Coming soon',isbn:'978-0-000000-00-1',accent:'wine'},
 {slug:'the-paragon-debt',title:'The Paragon Debt',series:'The Concealed Histories',position:2,description:'Every bargain leaves a record. This one was written in blood.',extended:'The Paragons are gathering and the Conclave is closing ranks. With two versions of the past and no safe allies, Mara must decide which lie is worth preserving.',quote:'Debts outlive the people foolish enough to incur them.',release:'Coming 2028',status:'Announced',accent:'forest'},
 {slug:'a-study-in-ash',title:'A Study in Ash',series:'Tales from the Archive',position:1,description:'Five accounts from the margins of supernatural history.',extended:'A collection of linked stories from Prague, Venice, Edinburgh and the forgotten rooms beneath the British Museum.',quote:'Ash is only evidence that has surrendered.',release:'Date withheld',status:'Unreleased',accent:'brown'}
];
export type Character={slug:string;name:string;group:string;summary:string;bio:string;firstAppearance:string;status:string;species:string;affiliation:string;quote:string;initials:string};
export const characterGroups=[{name:'The Conclave',description:'Custodians of the boundary between ordinary history and everything beneath it.'},{name:'The Paragons',description:'Revolutionaries, zealots, or liberators—depending on which archive survived.'},{name:'Unclassified',description:'Individuals whose loyalties resist convenient filing.'}];
export const characters:Character[]=[
 {slug:'mara-vane',name:'Mara Vane',group:'Unclassified',summary:'An unwilling inheritor with a talent for finding what was meant to stay lost.',bio:'Mara believed her father was an archivist. She was half right. His death leaves her with a brass key, a redacted name, and an inheritance the Conclave would prefer to retrieve quietly.',firstAppearance:'The Lazarus Covenant',status:'Under observation',species:'Human',affiliation:'Disputed',quote:'If it was meant to stay buried, someone should have chosen a better grave.',initials:'MV'},
 {slug:'elias-rook',name:'Elias Rook',group:'The Conclave',summary:'Keeper of the Seventh Archive and professional custodian of inconvenient truths.',bio:'Rook has served the Conclave long enough to remember three official versions of the same war. Courteous, exacting, and almost certainly dangerous.',firstAppearance:'The Lazarus Covenant',status:'Active',species:'Human',affiliation:'The Conclave',quote:'Secrecy is not silence. It is curation.',initials:'ER'},
 {slug:'lazarus',name:'Lazarus',group:'The Paragons',summary:'A name that appears wherever history suffers an unexplained correction.',bio:'There is no reliable account of Lazarus before 1891. There are, however, forty-seven mutually contradictory accounts after it.',firstAppearance:'The Lazarus Covenant',status:'Presumed dead',species:'Unknown',affiliation:'The Paragons',quote:'You call it history because you have forgotten who edited it.',initials:'L'},
 {slug:'vesper-saint',name:'Vesper Saint',group:'The Paragons',summary:'Diplomat, defector, and architect of the Blackwater armistice.',bio:'Vesper’s file is remarkable less for what it contains than for the seventeen missing pages in its centre.',firstAppearance:'The Paragon Debt',status:'At large',species:'Changed',affiliation:'The Paragons',quote:'Truth is merely a secret with poor security.',initials:'VS'}
];
export const articles=[
 {slug:'disturbances-beneath-highgate',title:'Regarding the disturbances beneath Highgate',date:'18 August 2026',category:'Field report',summary:'The official account mentions subsidence. The archive is less certain.',body:'At 03:14 on Sunday morning, three residents reported a sound beneath the eastern boundary wall. By dawn, the council had issued a statement concerning old drainage works. The Conclave issued no statement at all, which is generally more informative.'},
 {slug:'field-note-prague',title:'A field note from Prague',date:'02 July 2026',category:'Correspondence',summary:'Three vanished ledgers, a locked reading room, and one entirely innocent raven.',body:'The municipal archive insists the west reading room has been closed since 1964. The brass on its door is polished weekly. We leave readers to reconcile these facts.'},
 {slug:'lazarus-papers',title:'The Lazarus papers: first fragments',date:'21 May 2026',category:'Recovered papers',summary:'Newly recovered pages complicate an already inconvenient version of history.',body:'The fragments are written in three hands, two inks, and one language that has not been formally recognised since 1889. Transcription continues.'}
];
export const products=[{name:'The Lazarus Covenant',subtitle:'First edition hardback',price:'£19.99',category:'Books',availability:'Pre-order',tone:'wine'},{name:'Conclave Archive Print',subtitle:'Numbered A3 art print',price:'£28.00',category:'Prints',availability:'Available',tone:'forest'},{name:'Seventh Archive Bookplate',subtitle:'Antique-brass enamel pin',price:'£12.00',category:'Collectibles',availability:'Available',tone:'brass'}];
