create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table public.admin_users(id uuid primary key references auth.users(id) on delete cascade,email text not null,role text not null default 'editor' check(role in('editor','admin')),created_at timestamptz not null default now());
create or replace function public.is_shadowverse_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.admin_users where id=auth.uid() and role in('editor','admin')) $$;
grant execute on function public.is_shadowverse_admin() to anon,authenticated;

create table public.site_settings(id uuid primary key default gen_random_uuid(),key text unique not null,title text,value jsonb not null default '{}',seo jsonb not null default '{}',display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.homepage_sections(id uuid primary key default gen_random_uuid(),slug text unique not null,title text,eyebrow text,summary text,content jsonb not null default '{}',image_url text,image_alt text,display_order int not null default 0,is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.series(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,subtitle text,description text,hero_image_url text,hero_image_alt text,quote text,status text,display_order int not null default 0,is_published boolean not null default false,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.books(id uuid primary key default gen_random_uuid(),series_id uuid references public.series(id) on delete set null,slug text unique not null,title text not null,position int not null default 1,description text,extended_synopsis text,quote text,endorsement text,endorsement_source text,cover_url text,cover_alt text,release_date date,release_text text,publication_status text not null default 'unreleased' check(publication_status in('released','coming_soon','announced','unreleased')),isbn text,trailer_url text,additional_artwork jsonb not null default '[]',display_order int not null default 0,is_published boolean not null default false,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.book_purchase_links(id uuid primary key default gen_random_uuid(),book_id uuid not null references public.books(id) on delete cascade,label text not null,url text not null,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.character_groups(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,image_url text,image_alt text,accent_style text,display_order int not null default 0,is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.characters(id uuid primary key default gen_random_uuid(),group_id uuid references public.character_groups(id) on delete set null,slug text unique not null,name text not null,short_description text,full_description text,image_url text,image_alt text,first_appearance_id uuid references public.books(id) on delete set null,status text,species text,affiliation text,quote text,related_book_ids uuid[] not null default '{}',related_character_ids uuid[] not null default '{}',display_order int not null default 0,is_published boolean not null default false,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.news_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.news_articles(id uuid primary key default gen_random_uuid(),category_id uuid references public.news_categories(id) on delete set null,slug text unique not null,title text not null,hero_image_url text,hero_image_alt text,summary text,content text,publication_date timestamptz,author text,tags text[] not null default '{}',display_order int not null default 0,is_featured boolean not null default false,is_published boolean not null default false,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.product_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid references public.product_categories(id) on delete set null,slug text unique not null,name text not null,subtitle text,description text,main_image_url text,main_image_alt text,price numeric(12,2),currency text not null default 'GBP',availability text,purchase_url text,display_order int not null default 0,is_published boolean not null default false,seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,url text not null,alt_text text,caption text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.social_links(id uuid primary key default gen_random_uuid(),platform text not null,label text not null,url text not null,icon text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.cross_site_links(id uuid primary key default gen_random_uuid(),slug text unique not null default 'myriad',label text not null,supporting_text text,url text not null,open_in_new_tab boolean not null default true,icon text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table public.media(id uuid primary key default gen_random_uuid(),storage_path text unique not null,url text not null,filename text not null,mime_type text,size_bytes bigint,alt_text text,caption text,display_order int not null default 0,is_published boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);

do $$ declare t text; begin foreach t in array array['site_settings','homepage_sections','series','books','book_purchase_links','character_groups','characters','news_categories','news_articles','product_categories','products','product_images','social_links','cross_site_links','media'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select using (is_published=true and archived_at is null)','Public reads published '||t,t); execute format('create policy %I on public.%I for all to authenticated using (public.is_shadowverse_admin()) with check (public.is_shadowverse_admin())','Admins manage '||t,t); execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()','set_updated_at_'||t,t); end loop; end $$;
alter table public.admin_users enable row level security;
create policy "Admins read own membership" on public.admin_users for select to authenticated using(id=auth.uid());
create policy "Admins manage memberships" on public.admin_users for all to authenticated using(public.is_shadowverse_admin()) with check(public.is_shadowverse_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('media','media',true,10485760,array['image/jpeg','image/png','image/webp','image/avif','image/gif']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "Public reads Shadowverse media" on storage.objects for select using(bucket_id='media');
create policy "Admins upload Shadowverse media" on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_shadowverse_admin());
create policy "Admins update Shadowverse media" on storage.objects for update to authenticated using(bucket_id='media' and public.is_shadowverse_admin()) with check(bucket_id='media' and public.is_shadowverse_admin());
create policy "Admins delete Shadowverse media" on storage.objects for delete to authenticated using(bucket_id='media' and public.is_shadowverse_admin());

create index books_series_order_idx on public.books(series_id,display_order);create index characters_group_order_idx on public.characters(group_id,display_order);create index news_published_idx on public.news_articles(is_published,publication_date desc);create index products_category_order_idx on public.products(category_id,display_order);
